### ISSUE TITLE
Can't integrate easily, lots of non sense errors

### ISSUE THREAD

**Issue by HamedMP** [hkellaway/Gloss#101]
Please look at this question:

http://stackoverflow.com/questions/35200822/glossy-ios-doesnt-conform-to-protocol

**Comment by hkellaway** [comment]
hi @HamedMP - can you link me to a sample project where you're experiencing these issues?

**Comment by hkellaway** [comment]
As mentioned on StackOverflow - you're on Xcode 7.2 which comes with Swift 2.2. Gloss was last updated with Swift 2.1. I'll add a task for myself to update. If the functionality Gloss provides is needed before that happens, a different library should be used.

**Comment by Pericharan** [comment]
Hi hkellaway, first congratulations, its really nice library for json to object, but i am having issues when i convert object to Json with toJSON. The sample toJson is below. its creating ( brackets instead of { and has = sign instead of : in key value. So its not a valid json. Only URL are wrapped in double quotes other strings are not..  So could please help me clarify what setting needs to be set to get the correct json. Note: i ran your sample program i still got the same answer.. 
["products": (
 {
 "id_dt_ot_product" = 1;
 "product_image" = "HTTPS://UPLOAD.WIKIMEDIA.ORG/WIKIPEDIA/COMMONS/7/7C/CAPPUCCINO_CHIANG_MAI.JPG";
"product_name" = CAPPUCCINO;
}
)]

**Comment by hkellaway** [comment]
@Pericharan thanks! 

it sounds like what you're describing is simply what JSON looks like *when printed out in Xcode's console*. accessing that JSON *in code* would be as expected.

**Comment by hkellaway** [comment]
@HamedMP - so i ran the project with both Xcode 7.2 and 7.3, with no issues; so i'd say my theory is incorrect. 

if you try what this user on StackOverflow suggests and have any luck let me know http://stackoverflow.com/a/35201355/3777116

**Comment by hkellaway** [comment]
closing due to 2+ weeks of inactivity. the next version, `0.7.0` was just released - if desired, give that a try and submit another issue if you run into errors.
