### ISSUE TITLE
JSON property name with dot - ".meta"

### ISSUE THREAD

**Issue by jirizoudun** [hkellaway/Gloss#144]
Hi guys,
I need to parse JSON data that contains property named `.meta`. Other properties are parsed well but it seems that this particular name can't be parsed. My code is bellow.

```
struct MOSomeModel: Decodable {
    let meta: MOMeta?
    let data: MOData?
    
    init?(json: JSON) {
        self.meta = ".meta" <~~ json
        self.data = "data" <~~ json
    }
}

struct MOMeta: Decodable {   
    let currency: Currency?
   
    enum Currency: String {
        case Eur = "EUR"
    }
    
    init?(json: JSON) {
        self.currency = "currency" <~~ json
    }
}
```

Property named data is parsed well but meta property isn't. JSONData bellow.

```
{
    ".meta": {
        "currency": "EUR"
    },
    "data": {
        ... Something parsed well ...
    }
}
```

**Comment by hkellaway** [comment]
hey @jirizoudun -

this is because `.` is a special value for Gloss for keys - Gloss allows you to specify values nested in models by delimiting the key with a period (e.g. `self.myNestedValue = "outerModel.innerModel" <~~ json`) (see: https://github.com/hkellaway/Gloss#retrieving-nested-model-values-without-creating-extra-models)

you can get around that by creating your own transformer for that specific property (see: https://github.com/hkellaway/Gloss#custom-transformations). or, you can pass another value as the delimiting character instead of period - e.g.  here i'm indicating the delimiter should be `///`: `self.meta = Decoder.decodeDecodable(".meta", keyPathDelimiter: "///")(json)`

hope that helps!

**Comment by jirizoudun** [comment]
Ok, thank you for your help!

Have a nice day.
