### ISSUE TITLE
How is this any different from Mantle?

### ISSUE THREAD

**Issue by michaeleiselsc** [hkellaway/Gloss#27]
Seems like now we're just fragmenting the people who need this sort of library into the two libraries. This library, if it should exist in lieu of Mantle, should have an explanation of how it's different and the pros and cons of the two.

**Comment by hkellaway** [comment]
Mantle is implemented in Objective-C, this is implemented in Swift. I'm not sure how well Mantle works interoperating with Swift apps (this thread may be relevant: https://github.com/Mantle/Mantle/issues/421), but this would be for people wanting to use a Swift pod for the same purpose.

**Comment by michaeleiselsc** [comment]
Please figure all of this out then, before we risk needlessly splitting the developers on which library to use.

**Comment by hkellaway** [comment]
I don't feel it is a needless split - for folks wanting a Swift implementation, Mantle is not an option.

**Comment by hkellaway** [comment]
Let me know if you have more comments on the issue? Otherwise, I'll close out tomorrow. Thanks for bringing this up

**Comment by michaeleiselsc** [comment]
What are the pros of a Swift implementation, simply the ability to change Swift code if you want to change the library?

**Comment by hkellaway** [comment]
The implementation is purely Swift (which some would want), Swift users don't have to deal with Objective-C interoperability, the code base itself is smaller and easier to comprehend as a side-effect of it being Swift. I also don't believe that Mantle has to be the only library of this kind.

**Comment by morganchen12** [comment]
@michaeleiselsc If this library was an exact Swift port of Mantle, how would you propose this issue be resolved? By deleting this repository? Is there anything constructive that could come out of this question?

Even as a totally academic pursuit, it's worthwhile to have Swift ports of Objective-C libraries in order to highlight the differences between the two languages especially as Swift matures and especially as new developers and developers from other communities familiarize themselves with iOS and OS X development. In practicality, a relatively simple Swift library like this one may help newer developers learn how to contribute to open source codebases. This codebase makes extensive use of curried functions and other functional paradigms, which may help older object-oriented folk understand functional programming basics. 

At the very least, if this library becomes massively popular, it won't split the community any more than the introduction of Swift already has.

**Comment by fdiaz** [comment]
If you use Mantle, you'd need to subclass `MTLModel` which conforms to `NSObject`. If you want to use a lightweight struct for your data model, Mantle just won't work (as long as I'm aware).

I'd say that Mantle is a really good Objective-C solution for this problem, this library is trying to tackle the same problem from a Swift point of view.

**Comment by michaeleiselsc** [comment]
If there are API differences enabled by Swift, that's fine, I just wanted to make sure that there were.
